import { REVIEW_QUERIES } from './queries.js';
const limit=Number((process.argv.find(a=>a.startsWith('--limit='))||'--limit=100').split('=')[1]);
const supabaseUrl=process.env.SUPABASE_URL, supabaseKey=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY, braveKey=process.env.BRAVE_SEARCH_API_KEY;
if(!supabaseUrl||!supabaseKey||!braveKey)throw new Error('Set SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY (or SUPABASE_SECRET_KEY), and BRAVE_SEARCH_API_KEY');
async function sb(path,options={}){const res=await fetch(`${supabaseUrl}/rest/v1/${path}`,{...options,headers:{apikey:supabaseKey,Authorization:`Bearer ${supabaseKey}`,'Content-Type':'application/json',...(options.headers||{})}});if(!res.ok)throw new Error(`${res.status} ${await res.text()}`);if(res.status===204)return null;const body=await res.text();return body?JSON.parse(body):null}
function host(u){try{return new URL(u).hostname.toLowerCase().replace(/^www\./,'')}catch{return ''}}
function path(u){try{return new URL(u).pathname.toLowerCase()}catch{return ''}}
function source(u){const h=host(u);if(h==='trustpilot.com'||h.endsWith('.trustpilot.com'))return'trustpilot';if(h==='reddit.com'||h.endsWith('.reddit.com'))return'reddit';if(h==='yelp.com'||h.endsWith('.yelp.com'))return'yelp';if(h==='bbb.org'||h.endsWith('.bbb.org'))return'bbb';if(h==='sitejabber.com'||h.endsWith('.sitejabber.com'))return'sitejabber';return'third_party'}
function owned(u,d){const h=host(u);return h===d||h.endsWith(`.${d}`)}
function low(u){const p=path(u);return ['/products/','/collections/','/blogs/','/blog/','/pages/shipping','/pages/returns','/pages/refund','/shipping-policy','/return-policy','/refund-policy','/privacy-policy','/terms-of-service','/terms-and-conditions','/policies/','/faq','/help/'].some(x=>p.includes(x))}
const NEG=[/\bi was disappointed\b/i,/\bvery disappointed\b/i,/\bwould(?:n't| not) recommend\b/i,/\bnever received\b/i,/\bdid(?: not|n't) receive\b/i,/\bnever arrived\b/i,/\barrived (?:damaged|broken)\b/i,/\b(?:poor|terrible|bad) quality\b/i,/\bwrong size\b/i,/\btoo (?:small|large)\b/i,/\blate (?:delivery|shipping)\b/i,/\bshipping (?:took|was|is) .*?(?:late|slow|long)\b/i,/\bcustomer service (?:was|is) .*?(?:bad|poor|terrible|awful|unhelpful)\b/i,/\b(?:issue|problem) with\b/i,/\bnot as described\b/i,/\bnot worth\b/i,/\bwaste of money\b/i,/\bavoid (?:this|them|buying)\b/i,/\brefund .*?(?:never|did not|didn't)\b/i];
const CTX=/\b(i|i'm|my|me|we|our|ordered|order(?:ed)?|bought|purchased|received|package|delivery|shipment|customer|review|reviewer)\b/i;
function evidence(r,d){const u=r.url||'',text=`${r.title||''} — ${r.description||''}`.replace(/\s+/g,' ').trim();if(!u||!text||owned(u,d)||low(u))return null;const matches=NEG.filter(x=>x.test(text));if(!matches.length||!CTX.test(text))return null;const s=source(u),conf=Math.min(95,30+(s!=='third_party'?25:10)+Math.min(45,matches.length*15)+15);return{url:u,title:r.title||'',text:text.slice(0,1200),sourceType:s,matchedTerms:matches.map(x=>x.source),confidence:conf}}
async function brave(q){const u=new URL('https://api.search.brave.com/res/v1/web/search');u.searchParams.set('q',q);u.searchParams.set('count','8');const res=await fetch(u,{headers:{Accept:'application/json','X-Subscription-Token':braveKey}});if(!res.ok){console.warn(`Brave ${res.status} for ${q}`);return[]}const body=await res.text();if(!body.trim())return[];try{const d=JSON.parse(body);return Array.isArray(d?.web?.results)?d.web.results:[]}catch{console.warn(`Invalid Brave JSON for ${q}`);return[]}}
function brand(v,d){const x=String(v||d).replace(/&ndash;|&mdash;|&amp;|&quot;|&#39;/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();return x.replace(/\s*[|–—-]\s*(shopify|official|online store|store).*$/i,'').trim().slice(0,120)||d}
const prospects=await sb(`prospects?select=*&status=in.(qualified,priority)&order=qualification_score.desc&limit=${Math.max(1,Math.min(limit,100))}`);let researched=0,signals=0,queriesRun=0,candidates=0;
for(const p of prospects||[]){const existing=await sb(`prospect_signals?select=id&prospect_id=eq.${encodeURIComponent(p.id)}&signal_type=eq.customer_pain&limit=1`);if(existing?.length)continue;const found=new Map();for(const q of REVIEW_QUERIES(brand(p.store_name,p.domain),p.domain)){queriesRun++;let rs=[];try{rs=await brave(q)}catch(e){console.warn(`Evidence query failed: ${q}: ${e.message}`);continue}for(const r of rs){const e=evidence(r,p.domain);if(!e)continue;const k=`${host(e.url)}|${e.text.toLowerCase().replace(/\W+/g,' ').slice(0,350)}`;if(!found.has(k)||found.get(k).confidence<e.confidence)found.set(k,e)}}candidates+=found.size;const sorted=[...found.values()].sort((a,b)=>b.confidence-a.confidence).slice(0,8);for(const e of sorted){await sb('prospect_signals',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({prospect_id:p.id,signal_type:'customer_pain',signal_value:'public_customer_pain',confidence:e.confidence,evidence_url:e.url,evidence_text:e.text,metadata:{source:e.sourceType,title:e.title,matchedTerms:e.matchedTerms,evidenceVersion:'v3'}})});signals++}await sb(`prospects?id=eq.${encodeURIComponent(p.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:sorted.length?'researched':'qualified',metadata:{...(p.metadata||{}),evidenceResearch:{researchedAt:new Date().toISOString(),signalCount:sorted.length,candidateCount:found.size,source:'brave_search_v3',evidenceQuality:'third_party_customer_language'}},updated_at:new Date().toISOString()})});researched++}
console.log(JSON.stringify({researched,signals,queriesRun,candidates,evidenceVersion:'v3'},null,2));
