import { PAIN_QUERIES } from './queries.js';
const limit = Number((process.argv.find(a => a.startsWith('--limit=')) || '--limit=20').split('=')[1]);
const supabaseUrl = process.env.SUPABASE_URL, supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SECRET_KEY, braveKey = process.env.BRAVE_SEARCH_API_KEY;
if (!supabaseUrl || !supabaseKey || !braveKey) throw new Error('Set SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY (or SUPABASE_SECRET_KEY), and BRAVE_SEARCH_API_KEY');
async function sb(path, options = {}) { const res = await fetch(`${supabaseUrl}/rest/v1/${path}`, { ...options, headers: { apikey: supabaseKey, Authorization: `Bearer ${supabaseKey}`, 'Content-Type': 'application/json', ...(options.headers || {}) } }); if (!res.ok) throw new Error(`${res.status} ${await res.text()}`); return res.status === 204 ? null : res.json(); }
async function brave(q) { const u = new URL('https://api.search.brave.com/res/v1/web/search'); u.searchParams.set('q', q); u.searchParams.set('count', '5'); const res = await fetch(u, { headers: { Accept: 'application/json', 'X-Subscription-Token': braveKey } }); if (!res.ok) throw new Error(`Brave ${res.status}: ${await res.text()}`); const data = await res.json(); return (data.web?.results || []).map(x => ({ url: x.url, title: x.title, description: x.description })); }
const prospects = await sb(`prospects?select=*&status=in.(qualified,priority)&order=qualification_score.desc&limit=${Math.max(1, Math.min(limit, 100))}`);
let researched = 0, signals = 0;
for (const p of prospects) { const existing = await sb(`prospect_signals?select=id&prospect_id=eq.${encodeURIComponent(p.id)}&signal_type=eq.customer_pain&limit=1`); if (existing.length) continue; const seen = new Set(), found = [];
  for (const term of PAIN_QUERIES) { const results = await brave(`site:${p.domain} ${term}`); for (const r of results) { if (!r.url || seen.has(r.url)) continue; seen.add(r.url); const text = `${r.title || ''} ${r.description || ''}`; const hits = (text.match(/complaint|complaints|problem|problems|disappointed|return|refund|late|damaged|quality|sizing|size|shipping|delivery|service|issue|issues|wish/gi) || []).length; if (hits) found.push({ r, hits }); } if (found.length >= 8) break; }
  for (const item of found.slice(0, 8)) { const confidence = Math.min(95, 45 + item.hits * 10 + Math.min(found.length * 3, 20)); await sb('prospect_signals', { method: 'POST', headers: { Prefer: 'return=minimal' }, body: JSON.stringify({ prospect_id: p.id, signal_type: 'customer_pain', signal_value: 'public_review_or_complaint_signal', confidence, evidence_url: item.r.url, evidence_text: `${item.r.title || ''} — ${item.r.description || ''}`.slice(0, 1000), metadata: { title: item.r.title || '', keywordHits: item.hits, source: 'brave_search_v1' } }) }); signals++; }
  if (found.length) { const metadata = { ...(p.metadata || {}), evidenceResearch: { researchedAt: new Date().toISOString(), signalCount: found.length, source: 'brave_search_v1' } }; await sb(`prospects?id=eq.${encodeURIComponent(p.id)}`, { method: 'PATCH', headers: { Prefer: 'return=minimal' }, body: JSON.stringify({ status: 'researched', metadata, updated_at: new Date().toISOString() }) }); researched++; }
}
console.log(JSON.stringify({ researched, signals }, null, 2));
