export const DISCOVERY_QUERIES = [
  '"Powered by Shopify" "Trustpilot" fashion brand',
  '"Powered by Shopify" "Trustpilot" beauty brand',
  '"Powered by Shopify" "Trustpilot" skincare brand',
  '"Powered by Shopify" "Trustpilot" jewelry brand',
  '"Powered by Shopify" "Trustpilot" pet brand',
  '"Powered by Shopify" "Trustpilot" home decor brand',
  '"Powered by Shopify" "Judge.me" fashion brand',
  '"Powered by Shopify" "Judge.me" beauty brand',
  '"Powered by Shopify" "Judge.me" jewelry brand',
  '"Powered by Shopify" "Judge.me" pet brand',
  '"Powered by Shopify" "Yotpo" fashion brand',
  '"Powered by Shopify" "Yotpo" beauty brand',
  '"Powered by Shopify" "Loox" jewelry brand',
  '"Powered by Shopify" "Loox" pet brand',
  '"Shopify" "customer reviews" "Trustpilot" brand',
  '"Shopify" "verified reviews" brand',
  '"Shopify" "customer reviews" fashion store',
  '"Shopify" "customer reviews" beauty store',
  '"Shopify" "customer reviews" jewelry store',
  '"Shopify" "customer reviews" pet store',
  '"Shopify" "customer reviews" home decor store',
  '"Shopify" "customer reviews" fitness store',
  '"Shopify" "customer reviews" food store',
  '"Shopify" "customer reviews" supplement store',
];
