import { DISCOVERY_QUERIES } from './queries.js';
import { searchBrave } from './brave-provider.server.js';
import { inspectSite } from './site-inspector.server.js';

const limit = Number((process.argv.find(a => a.startsWith('--limit=')) || '--limit=100').split('=')[1]);
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SECRET_KEY;
const braveKey = process.env.BRAVE_SEARCH_API_KEY;
if (!supabaseUrl || !supabaseKey || !braveKey) throw new Error('Set SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY (or SUPABASE_SECRET_KEY), and BRAVE_SEARCH_API_KEY');
async function sb(path, options={}) { const res=await fetch(`${supabaseUrl}/rest/v1/${path}`,{...options,headers:{apikey:supabaseKey,Authorization:`Bearer ${supabaseKey}`,'Content-Type':'application/json',...(options.headers||{})}}); if(!res.ok) throw new Error(`${res.status} ${await res.text()}`); if(res.status===204)return null; const body=await res.text(); return body?JSON.parse(body):null; }
function hostOf(v){try{return new URL(v).hostname.toLowerCase().replace(/^www\./,'')}catch{return ''}}
function normalize(v){return hostOf(v).replace(/^shop\./,'')}
function bad(title='',url=''){const t=title.toLowerCase();let p='';try{p=new URL(url).pathname.toLowerCase()}catch{} return ['shopify app store','shopify apps','app directory','help center','documentation','developer','currency converter','translate your store','support center'].some(x=>t.includes(x))||['/apps/','/help/','/docs/','/documentation/','/developers/','/directory/'].some(x=>p.startsWith(x));}
const candidates=new Map();
for(const query of DISCOVERY_QUERIES){let results=[];try{results=await searchBrave(query,braveKey,{count:10})}catch(e){console.warn(`Discovery query failed: ${query}: ${e.message}`);continue} for(const r of results){const domain=normalize(r.url);if(!domain||bad(r.title,r.url)||domain==='shopify.com'||domain.endsWith('.shopify.com')||domain==='myshopify.com'||domain.endsWith('.myshopify.com'))continue;const c=candidates.get(domain)||{domain,urls:new Set(),titles:new Set(),queryHits:0};c.urls.add(r.url);if(r.title)c.titles.add(r.title);c.queryHits++;candidates.set(domain,c);if(candidates.size>=Math.max(limit*2,100))break}if(candidates.size>=Math.max(limit*2,100))break}
const selected=[...candidates.values()].sort((a,b)=>b.queryHits-a.queryHits).slice(0,Math.max(1,Math.min(limit,300)));
let verifiedShopify=0,priority=0;
for(const c of selected){try{const i=await inspectSite(`https://${c.domain}`);if(i.platform!=='shopify'||Number(i.platformConfidence||0)<50)continue;verifiedShopify++;const score=Math.min(100,Math.round(Math.min(Number(i.platformConfidence||0)*.45,45)+(i.reviewSignal?20:0)+(i.feedbackSignal?15:0)+(i.commerceSignal?10:0)+5));const status=score>=70?'priority':'qualified';if(status==='priority')priority++;const up=await sb('prospects?on_conflict=domain',{method:'POST',headers:{Prefer:'return=representation,resolution=merge-duplicates'},body:JSON.stringify({domain:c.domain,store_name:[...c.titles][0]||c.domain,platform:i.platform,platform_confidence:i.platformConfidence,review_signal:Boolean(i.reviewSignal),review_platform:i.reviewPlatform||null,feedback_signal:Boolean(i.feedbackSignal),commerce_signal:Boolean(i.commerceSignal),discovery_source:'brave_search',source_url:[...c.urls][0]||`https://${c.domain}`,qualification_score:score,status,metadata:{evidence:{discoveryQueryHits:c.queryHits,discoveryUrls:[...c.urls].slice(0,5),discoveryVersion:'v2'}},updated_at:new Date().toISOString()})});const p=Array.isArray(up)?up[0]:null;if(p?.id)await sb('prospect_sources',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({prospect_id:p.id,source_type:'discovery',source_url:[...c.urls][0]||`https://${c.domain}`,source_title:[...c.titles][0]||c.domain,metadata:{discoveryVersion:'v2',queryHits:c.queryHits}})})}catch(e){console.warn(`Candidate failed ${c.domain}: ${e.message}`)}}
console.log(JSON.stringify({discovered:selected.length,verifiedShopify,priority,discoveryVersion:'v2'},null,2));
